name: blackduck
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  blackduck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5.2.0
      with:
        python-version: '3.9'
        cache: 'pip'
    - name: Get Dependencies
      run: | 
        pip install -r requirements.txt
        pip list
    - name: Black Duck Scan
      uses: synopsys-sig/synopsys-action@v1.13.0
      env:
        DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
        DETECT_TOOLS: DETECTOR,THREAT_INTEL
        DETECT_PYTHON_PATH: /usr/bin/python3
        DETECT_THREATINTEL_SCAN_FILE_PATH: site-packages.tar.gz
      with:
        blackduck_url: ${{ vars.BLACKDUCK_URL }}
        blackduck_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
        blackduck_scan_failure_severities: 'ALL'
        blackduck_fixpr_enabled: true
        blackduck_prComment_enabled: true
        blackduck_reports_sarif_create: true
        blackduck_upload_sarif_report: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
